### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by thiviyanT** [deezer/linear_graph_autoencoders#1]
Hi, 

Are you still planning to make the code publicly available? 

Thanks, 
Thiviyan

**Comment by GuillaumeSalhaGalvan** [comment]
Dear Thiviyan,
The code is currently under review on our side, it should be available in the upcoming days.
Best,

Guillaume

**Comment by GuillaumeSalhaGalvan** [comment]
Dear Thiviyan,
The code is now available! I am closing this issue.
Best,

Guillaume
